In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

2.0.0+cu118


## Tensors

### Creating Tensors

https://pytorch.org/docs/stable/tensors.html

In [3]:
# Scalar tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# Number of tensor dimentions
scalar.ndim

0

In [5]:
# Get tensor back as py int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector.ndim

1

In [7]:
vector

tensor([7, 7])

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([
    [7,8],
    [9,11]
])
MATRIX

tensor([[ 7,  8],
        [ 9, 11]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 11])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
#  TENSOR
TENSOR = torch.tensor([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random tensors

Why random tensors?

Random tensors, потому что многие нейронки учатся, начиная с тенсоров онли из рандомных чисел и потом подправляют их значения, чтобы лучше соответствовать данным

`Start with random numbers -> look at data -> update random nums -> look at data -> update randoom nums`

In [17]:
# Create a random tensors of size (2,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1184, 0.2688, 0.5587, 0.2061],
        [0.6849, 0.2287, 0.5924, 0.4815],
        [0.2614, 0.4318, 0.1141, 0.5786]])

In [18]:
random_tensor2 = torch.rand(10, 1, 3)
random_tensor2

tensor([[[0.1494, 0.7210, 0.0436]],

        [[0.6911, 0.9075, 0.1458]],

        [[0.6648, 0.0853, 0.0447]],

        [[0.7203, 0.1300, 0.9386]],

        [[0.0685, 0.6952, 0.1862]],

        [[0.8130, 0.6247, 0.2429]],

        [[0.4996, 0.4623, 0.2653]],

        [[0.4334, 0.8327, 0.6943]],

        [[0.4359, 0.6719, 0.9803]],

        [[0.5350, 0.9365, 0.0318]]])

In [19]:
random_tensor.shape

torch.Size([3, 4])

In [20]:
random_tensor2.shape

torch.Size([10, 1, 3])

In [21]:
random_tensor2.ndim

3

In [22]:
# random tensor with similar shape to an image tensor
# size - optional keyword, not really needed
rnd_img_size_tensor = torch.rand(size=(224, 224, 3)) #h, w, color chanels
rnd_img_size_tensor.shape, rnd_img_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeroes and ones

In [23]:
# tensor of all zeros
zeros = torch.zeros(3,5)
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [24]:
ones = torch.ones(3,5)
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

### Creatingrange of tensors and tensors-like

In [25]:
# torch.range() rкак и python range()
x = torch.arange(0, 10, 2)
x

tensor([0, 2, 4, 6, 8])

In [26]:
# creating tensors-like, создает тенсор из нулей(например), такой-же формы(shape), как переданный тенсор
five_zeros = torch.zeros_like(x)
five_zeros

tensor([0, 0, 0, 0, 0])

### Tensor datatypes
##### 3 main issues when working with pytorrch and deep learning:
1. Tensors not right dtype
2. Tensors not right shape
3. Tensors not on the right device

In [27]:
#float 32
float_32_tensor = torch.tensor([1,3,3,7], dtype=torch.float32)
float_32_tensor

tensor([1., 3., 3., 7.])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
float_32_tensor2 = torch.tensor([1,3,3.,7])
float_32_tensor2

tensor([1., 3., 3., 7.])

In [30]:
float_32_tensor2.dtype

torch.float32

In [31]:
float_32_tensor3 = torch.tensor([1.1, 2.2, 3.3], 
                                dtype=None, #what datatype is tensor
                                device=None, #cpu or gpu(cuda)
                                requires_grad=False #whether or not to track gradients
                                )
float_32_tensor3

tensor([1.1000, 2.2000, 3.3000])

In [32]:
float_32_tensor3.dtype

torch.float32

In [33]:
float_16 = float_32_tensor.type(torch.float16)
float_16

tensor([1., 3., 3., 7.], dtype=torch.float16)

In [34]:
float_16.device

device(type='cpu')

### Manupulating Tensors (operations)

To find patterns in numbers of dataset, the neural network will usually combine all of this:

* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [35]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [36]:
# multiply by 10
tensor * 10

tensor([10, 20, 30])

In [37]:
tensor - 10

tensor([-9, -8, -7])

#### Marix Multiplication (dot product)

Чтобы перемножить матрицы, нам нужно найти так называемый dot product(cкалярное произведение) векторов
https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [38]:
# Element-wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [39]:
# matrix multiplication (dot product) сначала перемножаем элементы как в примере выше, потом складываем результаты умножения
torch.matmul(tensor, tensor)

tensor(14)

In [40]:
# pytorch methods are very optimized:
%%time
val = 0
for i in range(len(tensor)):   
    val += tensor[i]*tensor[i]
print(val)

tensor(14)
CPU times: user 2.09 ms, sys: 12 µs, total: 2.1 ms
Wall time: 3.17 ms


In [41]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 27 µs, sys: 5 µs, total: 32 µs
Wall time: 35.5 µs


tensor(14)

### Two main rules for matrix multiplication:
1. The **inner dimentions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimentions**:
* `(2, 3) @ (3, 2)` -> shape(3, 3)
* `(2, 2) @ (2, 3)` -> shape(2, 3)

In [42]:
torch.matmul(torch.rand(2,2), torch.rand(2,3))

tensor([[0.0915, 1.0365, 0.7525],
        [0.0748, 0.7168, 0.5329]])

In [43]:
torch.rand(2,2)

tensor([[7.8499e-05, 9.7082e-01],
        [3.2869e-01, 3.1348e-01]])

In [44]:
torch.rand(2,3)

tensor([[0.1497, 0.2582, 0.1639],
        [0.1776, 0.2252, 0.7595]])

In [45]:
tensor_A = torch.tensor([
    [1,2],
    [3,4],
    [5,6]
])

In [46]:
tensor_B = torch.tensor([
    [7,8],
    [8,9],
    [9,9]
])

In [47]:
# torch.mm - alias for matmul
# torch.mm(tensor_A, tensor_B)

In [48]:
# RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)
# To fix this we can manipulate on of the tensors using a **transpose**

In [49]:
# transpose switches the axes or dimentions of a given tensor
tensor_B

tensor([[7, 8],
        [8, 9],
        [9, 9]])

In [50]:
# T - transpose
tensor_B.T

tensor([[7, 8, 9],
        [8, 9, 9]])

In [51]:
# Теперь ошибки нету, т.к. мы изменили форму тенсора B
torch.mm(tensor_A, tensor_B.T)

tensor([[23, 26, 27],
        [53, 60, 63],
        [83, 94, 99]])

## Finding min, max, mean, sum etc (tensor aggregation)

In [52]:
# Create a tensor
t = torch.arange(0, 100, 10)
t, t.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [53]:
# find min and max
t.min(), torch.min(t)

(tensor(0), tensor(0))

In [54]:
t.max(), torch.max(t)

(tensor(90), tensor(90))

In [55]:
# t.mean(), torch.mean(t)
# RuntimeError: mean(): could not infer output dtype. Input dtype must be either 
# a floating point or complex dtype. Got: Long

In [56]:
torch.mean(t, dtype=torch.float32), torch.mean(t.type(torch.float32))

(tensor(45.), tensor(45.))

In [57]:
# sum
t.sum(), torch.sum(t)

(tensor(450), tensor(450))

In [58]:
# finding indicies of min max
t.argmin()

tensor(0)

In [59]:
t.argmax()

tensor(9)

## reshaping, stacking, squeezing, unsqueezing
* Reshaping - rashapes tensor to a defined form
* View - return a view of a tensor of certain shape, not changing anything
* Stacking - combine multiple tensors on top of each other(vstack) or side by side (hstach)
* Squeeze - removes all single dimentions from a tensor
* Unsqueeze - adds a single dimention to a target tensor
* Permute - return a view of the input with dimentions permuted (swapped) in a certain way

In [60]:
import torch
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [61]:
# Add an extra dimention
# т.к оригинальный тенсор формы просто 10, то его можно разбить на 2 и 5 или 1 и 10 или 10 и 1, w/e
x_reshaped = x.reshape(5, 2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [62]:
# Change the view - тот же результат, чтолько мы обращаемся к той же ячейки памяти, где и х
z = x.view(5, 2)
z, z.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [63]:
# Таким образом, поменяв z, мы поменяем и x
z[:, 0] = 5
z, x

(tensor([[ 5.,  2.],
         [ 5.,  4.],
         [ 5.,  6.],
         [ 5.,  8.],
         [ 5., 10.]]),
 tensor([ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.]))

In [64]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x])
x_stacked, x_stacked.shape

(tensor([[ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.],
         [ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.],
         [ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.]]),
 torch.Size([3, 10]))

In [65]:
# optional attribute dim=
x_stacked = torch.stack([x], dim=1)
x_stacked, x_stacked.shape
# это как hstack и vstack

(tensor([[ 5.],
         [ 2.],
         [ 5.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 5.],
         [ 8.],
         [ 5.],
         [10.]]),
 torch.Size([10, 1]))

In [66]:
# squeeze
# The returned tensor shares the storage with the input tensor, so changing the contents of one will change the contents of the other.
sq = x_stacked.squeeze()
sq, sq.shape

(tensor([ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.]), torch.Size([10]))

In [67]:
# torch.unsqueeze 
unsq = sq.unsqueeze(dim=0)
unsq, unsq.shape

(tensor([[ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.]]),
 torch.Size([1, 10]))

In [68]:
unsq = sq.unsqueeze(dim=1)
unsq, unsq.shape

(tensor([[ 5.],
         [ 2.],
         [ 5.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 5.],
         [ 8.],
         [ 5.],
         [10.]]),
 torch.Size([10, 1]))

In [69]:
# permute - returns a View! of the original tensor  with dimentions permuted(rearranged)
a = torch.randn(2, 3, 5)
a, a.shape

(tensor([[[ 0.6717,  0.7379,  0.2934, -0.0106,  0.2557],
          [-1.8765,  1.1827, -0.1308,  0.3785, -1.2129],
          [ 1.5523,  0.7643, -0.7788,  1.4559,  1.1180]],
 
         [[ 0.7392,  1.1062,  0.9759, -0.2611,  1.1464],
          [-0.4060,  0.5459, -1.2011,  0.0052,  0.6816],
          [-0.0837,  0.0263,  0.0562, -1.8841, -0.4475]]]),
 torch.Size([2, 3, 5]))

In [70]:
b = a.permute((2, 0, 1))
# b = torch.permute(a, (2, 0, 1))

In [71]:
b, b.shape

(tensor([[[ 0.6717, -1.8765,  1.5523],
          [ 0.7392, -0.4060, -0.0837]],
 
         [[ 0.7379,  1.1827,  0.7643],
          [ 1.1062,  0.5459,  0.0263]],
 
         [[ 0.2934, -0.1308, -0.7788],
          [ 0.9759, -1.2011,  0.0562]],
 
         [[-0.0106,  0.3785,  1.4559],
          [-0.2611,  0.0052, -1.8841]],
 
         [[ 0.2557, -1.2129,  1.1180],
          [ 1.1464,  0.6816, -0.4475]]]),
 torch.Size([5, 2, 3]))

In [72]:
x_original = torch.rand((224, 224, 3)) # - height, width, color_channels
x_original, x_original.shape

(tensor([[[0.2934, 0.1420, 0.1630],
          [0.1198, 0.7428, 0.2655],
          [0.0206, 0.8408, 0.3721],
          ...,
          [0.6562, 0.3764, 0.3460],
          [0.7521, 0.2478, 0.3201],
          [0.9615, 0.9255, 0.6735]],
 
         [[0.6918, 0.8791, 0.8038],
          [0.1998, 0.4859, 0.9126],
          [0.2649, 0.0042, 0.9975],
          ...,
          [0.4582, 0.9025, 0.3356],
          [0.5032, 0.1030, 0.6557],
          [0.1519, 0.1956, 0.8974]],
 
         [[0.9286, 0.8778, 0.1084],
          [0.5349, 0.7359, 0.3201],
          [0.7674, 0.0450, 0.7094],
          ...,
          [0.9624, 0.4910, 0.2239],
          [0.0110, 0.9807, 0.6165],
          [0.2596, 0.3339, 0.2961]],
 
         ...,
 
         [[0.7121, 0.6670, 0.0201],
          [0.3237, 0.8547, 0.6065],
          [0.5789, 0.9490, 0.5989],
          ...,
          [0.1782, 0.7890, 0.0466],
          [0.4911, 0.6443, 0.8089],
          [0.2099, 0.5039, 0.6225]],
 
         [[0.2738, 0.7568, 0.2055],
          [0

In [73]:
x_permuted = x_original.permute(2, 0, 1)
x_permuted, x_permuted.shape

(tensor([[[0.2934, 0.1198, 0.0206,  ..., 0.6562, 0.7521, 0.9615],
          [0.6918, 0.1998, 0.2649,  ..., 0.4582, 0.5032, 0.1519],
          [0.9286, 0.5349, 0.7674,  ..., 0.9624, 0.0110, 0.2596],
          ...,
          [0.7121, 0.3237, 0.5789,  ..., 0.1782, 0.4911, 0.2099],
          [0.2738, 0.2282, 0.0943,  ..., 0.2664, 0.7373, 0.5911],
          [0.4804, 0.0975, 0.6310,  ..., 0.4003, 0.8185, 0.0559]],
 
         [[0.1420, 0.7428, 0.8408,  ..., 0.3764, 0.2478, 0.9255],
          [0.8791, 0.4859, 0.0042,  ..., 0.9025, 0.1030, 0.1956],
          [0.8778, 0.7359, 0.0450,  ..., 0.4910, 0.9807, 0.3339],
          ...,
          [0.6670, 0.8547, 0.9490,  ..., 0.7890, 0.6443, 0.5039],
          [0.7568, 0.4777, 0.3887,  ..., 0.9200, 0.0827, 0.1542],
          [0.6797, 0.6837, 0.9013,  ..., 0.0432, 0.1195, 0.0716]],
 
         [[0.1630, 0.2655, 0.3721,  ..., 0.3460, 0.3201, 0.6735],
          [0.8038, 0.9126, 0.9975,  ..., 0.3356, 0.6557, 0.8974],
          [0.1084, 0.3201, 0.7094,  ...,

In [74]:
# Наопминалка - permuted в той же ячейке памяти

## Indexing, similar to numpy

In [75]:
# create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3) #1x3x3 = 9
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [76]:
# lets index into our tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [77]:
# lets index in the middle
x[0, 1], x[0][1]

(tensor([4, 5, 6]), tensor([4, 5, 6]))

In [78]:
# index of 5
x[0, 1, 1], x[0][1][1]

(tensor(5), tensor(5))

In [79]:
# we can use : to access all indecies of selected dimention

In [80]:
# take all of 0 and 1 dims and only 1st indecies of 2nd dim
x[:, :, 1]

tensor([[2, 5, 8]])

In [81]:
# all from 0 but only 1 index from 1d and 2d
x[:, 1, 1]

tensor([5])

## Pytorch tensors and NumPy

* Data in Numpy - want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* From torch to NumPy -> `torch.Tensor.numpy()`


In [82]:
import torch
import numpy as np

array = np.arange(1., 8.)
tensor = torch.from_numpy(array) # to make default torch dtype - .type(torch.float32)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [83]:
array.dtype

dtype('float64')

In [84]:
torch.arange(1., 8.).dtype

torch.float32

In [85]:
# Change the value of array, what will it do to `tensor` ? (same with tensor to numpy)

In [86]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [87]:
# tensor to NumPy
tensor = torch.arange(1,5)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1, 2, 3, 4]), array([1, 2, 3, 4]))

## Reproducebility (trying to take random out of random)

Нейронка обучается так (вкратце):

`start with random numbers -> tensor operations -> update random numbersto try make them a better representation of the data -> repeat`

Чтобы уменьшить рандомность, юзаeтся так называемый` **random seed**

In [88]:
# create 2 rand tensors
rnd_tensor_A = torch.rand(3, 4)
rnd_tensor_B = torch.rand(3, 4)

print('tensor A:\n\n', rnd_tensor_A, '\n')
print('tensor B:\n\n', rnd_tensor_B, '\n') 
print(rnd_tensor_A == rnd_tensor_B)

tensor A:

 tensor([[0.5616, 0.8115, 0.2080, 0.8356],
        [0.6714, 0.3083, 0.5582, 0.3387],
        [0.7789, 0.6065, 0.7060, 0.2615]]) 

tensor B:

 tensor([[0.9499, 0.8047, 0.6745, 0.5051],
        [0.0071, 0.5719, 0.5156, 0.9135],
        [0.6913, 0.2269, 0.1533, 0.4223]]) 

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [89]:
# Now lets make some random, but reproducible tensors:
import torch

# set the random seed
RANDOM_SEED = 88

torch.manual_seed(RANDOM_SEED)
rnd_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
rnd_tensor_D = torch.rand(3, 4)

print('tensor C:\n\n', rnd_tensor_C, '\n')
print('tensor D:\n\n', rnd_tensor_D, '\n') 
print(rnd_tensor_C == rnd_tensor_D)

tensor C:

 tensor([[0.7731, 0.6937, 0.8303, 0.4142],
        [0.2554, 0.0190, 0.4490, 0.8893],
        [0.1977, 0.2397, 0.8601, 0.3128]]) 

tensor D:

 tensor([[0.7731, 0.6937, 0.8303, 0.4142],
        [0.2554, 0.0190, 0.4490, 0.8893],
        [0.1977, 0.2397, 0.8601, 0.3128]]) 

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [90]:
#  https://pytorch.org/docs/stable/notes/randomness.html

In [91]:
# Check for GPU access with pytorch
torch.cuda.is_available()

True

In [96]:
# sETUP DEVICE AGNOSTIC CODE 
device = "cuda" if torch.cuda.is_available() else "cpu"

In [97]:
device

'cuda'

## Putting tensors and models on the GPU

In [104]:
# Create tensor (def=cpu)
tensor = torch.tensor([1, 2 ,3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [105]:
# Move tensor to GPU
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [108]:
# back to CPU (If tensor on GPU, can't transform it to NumPy)!!!!!!!!!!!!!!!!!!!!!!!
# tensor_on_cpu = tensor_on_gpu.to('cpu')
tensor_on_cpu = tensor_on_gpu.cpu()
tensor_on_cpu.device, tensor_on_gpu

(device(type='cpu'), tensor([1, 2, 3], device='cuda:0'))

In [109]:
# Exercises

# 2) Create a random tensor with shape (7, 7).
x = torch.randn(7, 7)
x, x.shape

(tensor([[ 0.0631,  2.8513, -0.2867,  0.0621,  1.8978,  0.4031, -1.4297],
         [ 1.9329, -1.4254, -0.5128, -0.0562,  2.1525,  0.2407, -0.9002],
         [-2.0012, -1.4268,  0.5157, -0.9045,  0.8949, -0.2031, -1.3303],
         [-0.0798,  0.8719, -1.3089, -0.7088, -1.0707,  0.6845,  0.4388],
         [-0.7025, -0.1489,  0.0930,  1.7277, -0.4068,  0.8536, -0.6982],
         [-1.7014, -2.6704, -1.4788,  0.0608,  0.6590, -1.7416, -0.9727],
         [ 1.3185, -1.5648, -0.5592, -0.0073,  0.6782,  0.2615,  0.5007]]),
 torch.Size([7, 7]))

In [111]:
# 3) Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

# Element-wise multiplication:
y = x * torch.randn(1, 7)
y, y.shape

(tensor([[ 0.1440,  3.6657, -0.0410,  0.1226,  0.4858, -0.6724, -1.4850],
         [ 4.4114, -1.8325, -0.0733, -0.1109,  0.5510, -0.4015, -0.9350],
         [-4.5675, -1.8343,  0.0737, -1.7865,  0.2291,  0.3388, -1.3817],
         [-0.1822,  1.1210, -0.1870, -1.3999, -0.2741, -1.1417,  0.4558],
         [-1.6033, -0.1915,  0.0133,  3.4124, -0.1041, -1.4237, -0.7252],
         [-3.8830, -3.4331, -0.2113,  0.1201,  0.1687,  2.9049, -1.0103],
         [ 3.0092, -2.0117, -0.0799, -0.0144,  0.1736, -0.4361,  0.5201]]),
 torch.Size([7, 7]))

In [115]:
# MatMul for a dot product:
y = torch.mm(x, torch.randn(1, 7).T)
y, y.shape

(tensor([[-4.0713],
         [-3.6968],
         [-3.1263],
         [ 0.5045],
         [ 1.9110],
         [-0.4840],
         [-0.0790]]),
 torch.Size([7, 1]))

In [131]:
#6)  Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? 
# (hint: you'll need to look into the documentation for torch.cuda for this one). 
# if there is, set the GPU random seed to 1234.

# setting seed for gpu
GPU_SEED = 1234
torch.manual_seed(GPU_SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed(GPU_SEED)

# Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). 
# Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

rdn_tensor_A = torch.randn(2, 3).cuda()
rdn_tensor_B = torch.randn(2, 3).cuda()

rdn_tensor_A, rdn_tensor_B

(tensor([[ 0.0461,  0.4024, -1.0115],
         [ 0.2167, -0.6123,  0.5036]], device='cuda:0'),
 tensor([[ 0.2310,  0.6931, -0.2669],
         [ 2.1785,  0.1021, -0.2590]], device='cuda:0'))

In [134]:
# 7) Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors)
kek = torch.matmul(rdn_tensor_A, rdn_tensor_B.T)
kek, kek.shape

(tensor([[ 0.5595,  0.4036],
         [-0.5087,  0.2792]], device='cuda:0'),
 torch.Size([2, 2]))

In [137]:
# Find the maximum and minimum values of the output of 7.
kek.min(), kek.max()

(tensor(-0.5087, device='cuda:0'), tensor(0.5595, device='cuda:0'))

In [138]:
# Find the maximum and minimum index values of the output of 7.
torch.argmin(kek), torch.argmax(kek)

(tensor(2, device='cuda:0'), tensor(0, device='cuda:0'))

In [141]:
# Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). 
x = torch.rand(1, 1, 1, 10)
x, x.shape

(tensor([[[[0.5247, 0.6688, 0.8436, 0.4265, 0.9561, 0.0770, 0.4108, 0.0014,
            0.5414, 0.6419]]]]),
 torch.Size([1, 1, 1, 10]))

In [142]:
x_squeezed = x.squeeze()
x_squeezed, x_squeezed.shape

(tensor([0.5247, 0.6688, 0.8436, 0.4265, 0.9561, 0.0770, 0.4108, 0.0014, 0.5414,
         0.6419]),
 torch.Size([10]))

In [143]:
# Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
SEED = 7
torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed(SEED)

x = torch.rand(1, 1, 1, 10)
x, x.shape

(tensor([[[[0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006, 0.0518, 0.4681,
            0.6738, 0.3315]]]]),
 torch.Size([1, 1, 1, 10]))

In [144]:
x_squeezed = x.squeeze()
x_squeezed, x_squeezed.shape

(tensor([0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006, 0.0518, 0.4681, 0.6738,
         0.3315]),
 torch.Size([10]))