In [54]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [55]:
print(torch.__version__)

1.13.1+cu116


## Tensors

### Creating Tensors

https://pytorch.org/docs/stable/tensors.html

In [56]:
# Scalar tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [57]:
# Number of tensor dimentions
scalar.ndim

0

In [58]:
# Get tensor back as py int
scalar.item()

7

In [59]:
# Vector
vector = torch.tensor([7,7])
vector.ndim

1

In [60]:
vector

tensor([7, 7])

In [61]:
vector.shape

torch.Size([2])

In [62]:
# MATRIX
MATRIX = torch.tensor([
    [7,8],
    [9,11]
])
MATRIX

tensor([[ 7,  8],
        [ 9, 11]])

In [63]:
MATRIX.ndim

2

In [64]:
MATRIX[1]

tensor([ 9, 11])

In [65]:
MATRIX.shape

torch.Size([2, 2])

In [66]:
#  TENSOR
TENSOR = torch.tensor([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [67]:
TENSOR.ndim

3

In [68]:
TENSOR.shape

torch.Size([1, 3, 3])

In [69]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random tensors

Why random tensors?

Random tensors, потому что многие нейронки учатся, начиная с тенсоров онли из рандомных чисел и потом подправляют их значения, чтобы лучше соответствовать данным

`Start with random numbers -> look at data -> update random nums -> look at data -> update randoom nums`

In [70]:
# Create a random tensors of size (2,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8995, 0.8710, 0.8192, 0.7102],
        [0.4932, 0.3711, 0.6508, 0.4044],
        [0.6051, 0.4668, 0.1103, 0.0488]])

In [71]:
random_tensor2 = torch.rand(10, 1, 3)
random_tensor2

tensor([[[0.5418, 0.6101, 0.8343]],

        [[0.3051, 0.0751, 0.3073]],

        [[0.8202, 0.2830, 0.3962]],

        [[0.0338, 0.5819, 0.2977]],

        [[0.6914, 0.1128, 0.8215]],

        [[0.3445, 0.3474, 0.8393]],

        [[0.1064, 0.4708, 0.6883]],

        [[0.7650, 0.8000, 0.8538]],

        [[0.0190, 0.3461, 0.4918]],

        [[0.7041, 0.3958, 0.3917]]])

In [72]:
random_tensor.shape

torch.Size([3, 4])

In [73]:
random_tensor2.shape

torch.Size([10, 1, 3])

In [74]:
random_tensor2.ndim

3

In [75]:
# random tensor with similar shape to an image tensor
# size - optional keyword, not really needed
rnd_img_size_tensor = torch.rand(size=(224, 224, 3)) #h, w, color chanels
rnd_img_size_tensor.shape, rnd_img_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeroes and ones

In [76]:
# tensor of all zeros
zeros = torch.zeros(3,5)
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [77]:
ones = torch.ones(3,5)
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

### Creatingrange of tensors and tensors-like

In [78]:
# torch.range() rкак и python range()
x = torch.arange(0, 10, 2)
x

tensor([0, 2, 4, 6, 8])

In [79]:
# creating tensors-like, создает тенсор из нулей(например), такой-же формы(shape), как переданный тенсор
five_zeros = torch.zeros_like(x)
five_zeros

tensor([0, 0, 0, 0, 0])

### Tensor datatypes
##### 3 main issues when working with pytorrch and deep learning:
1. Tensors not right dtype
2. Tensors not right shape
3. Tensors not on the right device

In [80]:
#float 32
float_32_tensor = torch.tensor([1,3,3,7], dtype=torch.float32)
float_32_tensor

tensor([1., 3., 3., 7.])

In [81]:
float_32_tensor.dtype

torch.float32

In [82]:
float_32_tensor2 = torch.tensor([1,3,3.,7])
float_32_tensor2

tensor([1., 3., 3., 7.])

In [83]:
float_32_tensor2.dtype

torch.float32

In [84]:
float_32_tensor3 = torch.tensor([1.1, 2.2, 3.3], 
                                dtype=None, #what datatype is tensor
                                device=None, #cpu or gpu(cuda)
                                requires_grad=False #whether or not to track gradients
                                )
float_32_tensor3

tensor([1.1000, 2.2000, 3.3000])

In [85]:
float_32_tensor3.dtype

torch.float32

In [86]:
float_16 = float_32_tensor.type(torch.float16)
float_16

tensor([1., 3., 3., 7.], dtype=torch.float16)

In [87]:
float_16.device

device(type='cpu')

### Manupulating Tensors (operations)

To find patterns in numbers of dataset, the neural network will usually combine all of this:

* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [88]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [89]:
# multiply by 10
tensor * 10

tensor([10, 20, 30])

In [90]:
tensor - 10

tensor([-9, -8, -7])

#### Marix Multiplication (dot product)

Чтобы перемножить матрицы, нам нужно найти так называемый dot product(cкалярное произведение) векторов
https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [91]:
# Element-wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [92]:
# matrix multiplication (dot product) сначала перемножаем элементы как в примере выше, потом складываем результаты умножения
torch.matmul(tensor, tensor)

tensor(14)

In [93]:
# pytorch methods are very optimized:
%%time
val = 0
for i in range(len(tensor)):   
    val += tensor[i]*tensor[i]
print(val)

tensor(14)
CPU times: user 1.79 ms, sys: 0 ns, total: 1.79 ms
Wall time: 2.44 ms


In [94]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 96 µs, sys: 13 µs, total: 109 µs
Wall time: 746 µs


tensor(14)

### Two main rules for matrix multiplication:
1. The **inner dimentions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimentions**:
* `(2, 3) @ (3, 2)` -> shape(3, 3)
* `(2, 2) @ (2, 3)` -> shape(2, 3)

In [95]:
torch.matmul(torch.rand(2,2), torch.rand(2,3))

tensor([[1.0140, 0.1518, 0.8795],
        [1.1473, 0.1160, 0.4467]])

In [96]:
torch.rand(2,2)

tensor([[0.8488, 0.4618],
        [0.8011, 0.0542]])

In [97]:
torch.rand(2,3)

tensor([[0.3938, 0.1892, 0.7877],
        [0.8625, 0.5115, 0.1618]])

In [98]:
tensor_A = torch.tensor([
    [1,2],
    [3,4],
    [5,6]
])

In [99]:
tensor_B = torch.tensor([
    [7,8],
    [8,9],
    [9,9]
])

In [100]:
# torch.mm - alias for matmul
# torch.mm(tensor_A, tensor_B)

In [101]:
# RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)
# To fix this we can manipulate on of the tensors using a **transpose**

In [102]:
# transpose switches the axes or dimentions of a given tensor
tensor_B

tensor([[7, 8],
        [8, 9],
        [9, 9]])

In [103]:
# T - transpose
tensor_B.T

tensor([[7, 8, 9],
        [8, 9, 9]])

In [104]:
# Теперь ошибки нету, т.к. мы изменили форму тенсора B
torch.mm(tensor_A, tensor_B.T)

tensor([[23, 26, 27],
        [53, 60, 63],
        [83, 94, 99]])

## Finding min, max, mean, sum etc (tensor aggregation)

In [112]:
# Create a tensor
t = torch.arange(0, 100, 10)
t, t.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [109]:
# find min and max
t.min(), torch.min(t)

(tensor(0), tensor(0))

In [111]:
t.max(), torch.max(t)

(tensor(90), tensor(90))

In [114]:
# t.mean(), torch.mean(t)
# RuntimeError: mean(): could not infer output dtype. Input dtype must be either 
# a floating point or complex dtype. Got: Long

In [119]:
torch.mean(t, dtype=torch.float32), torch.mean(t.type(torch.float32))

(tensor(45.), tensor(45.))

In [120]:
# sum
t.sum(), torch.sum(t)

(tensor(450), tensor(450))