In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
print(torch.__version__)

1.13.1+cu116


## Tensors

### Creating Tensors

https://pytorch.org/docs/stable/tensors.html

In [4]:
# Scalar tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
# Number of tensor dimentions
scalar.ndim

0

In [6]:
# Get tensor back as py int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7,7])
vector.ndim

1

In [8]:
vector

tensor([7, 7])

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([
    [7,8],
    [9,11]
])
MATRIX

tensor([[ 7,  8],
        [ 9, 11]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([ 9, 11])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
#  TENSOR
TENSOR = torch.tensor([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random tensors

Why random tensors?

Random tensors, потому что многие нейронки учатся, начиная с тенсоров онли из рандомных чисел и потом подправляют их значения, чтобы лучше соответствовать данным

`Start with random numbers -> look at data -> update random nums -> look at data -> update randoom nums`

In [18]:
# Create a random tensors of size (2,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9303, 0.6312, 0.2567, 0.4004],
        [0.7425, 0.4821, 0.4996, 0.5484],
        [0.1018, 0.2161, 0.8289, 0.6017]])

In [19]:
random_tensor2 = torch.rand(10, 1, 3)
random_tensor2

tensor([[[0.7732, 0.8737, 0.4769]],

        [[0.8011, 0.3485, 0.3392]],

        [[0.8880, 0.5177, 0.5678]],

        [[0.4136, 0.4272, 0.1099]],

        [[0.9913, 0.8208, 0.2744]],

        [[0.3603, 0.2915, 0.2791]],

        [[0.0963, 0.9147, 0.6771]],

        [[0.1343, 0.6710, 0.0836]],

        [[0.7782, 0.5521, 0.5671]],

        [[0.0641, 0.2776, 0.4021]]])

In [20]:
random_tensor.shape

torch.Size([3, 4])

In [21]:
random_tensor2.shape

torch.Size([10, 1, 3])

In [22]:
random_tensor2.ndim

3

In [23]:
# random tensor with similar shape to an image tensor
# size - optional keyword, not really needed
rnd_img_size_tensor = torch.rand(size=(224, 224, 3)) #h, w, color chanels
rnd_img_size_tensor.shape, rnd_img_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeroes and ones

In [24]:
# tensor of all zeros
zeros = torch.zeros(3,5)
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [25]:
ones = torch.ones(3,5)
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

### Creatingrange of tensors and tensors-like

In [26]:
# torch.range() rкак и python range()
x = torch.arange(0, 10, 2)
x

tensor([0, 2, 4, 6, 8])

In [27]:
# creating tensors-like, создает тенсор из нулей(например), такой-же формы(shape), как переданный тенсор
five_zeros = torch.zeros_like(x)
five_zeros

tensor([0, 0, 0, 0, 0])

### Tensor datatypes
##### 3 main issues when working with pytorrch and deep learning:
1. Tensors not right dtype
2. Tensors not right shape
3. Tensors not on the right device

In [28]:
#float 32
float_32_tensor = torch.tensor([1,3,3,7], dtype=torch.float32)
float_32_tensor

tensor([1., 3., 3., 7.])

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_32_tensor2 = torch.tensor([1,3,3.,7])
float_32_tensor2

tensor([1., 3., 3., 7.])

In [31]:
float_32_tensor2.dtype

torch.float32

In [32]:
float_32_tensor3 = torch.tensor([1.1, 2.2, 3.3], 
                                dtype=None, #what datatype is tensor
                                device=None, #cpu or gpu(cuda)
                                requires_grad=False #whether or not to track gradients
                                )
float_32_tensor3

tensor([1.1000, 2.2000, 3.3000])

In [33]:
float_32_tensor3.dtype

torch.float32

In [34]:
float_16 = float_32_tensor.type(torch.float16)
float_16

tensor([1., 3., 3., 7.], dtype=torch.float16)

In [35]:
float_16.device

device(type='cpu')

### Manupulating Tensors (operations)

To find patterns in numbers of dataset, the neural network will usually combine all of this:

* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [36]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [37]:
# multiply by 10
tensor * 10

tensor([10, 20, 30])

In [38]:
tensor - 10

tensor([-9, -8, -7])

#### Marix Multiplication (dot product)

Чтобы перемножить матрицы, нам нужно найти так называемый dot product(cкалярное произведение) векторов
https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [39]:
# Element-wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [41]:
# matrix multiplication (dot product) сначала перемножаем элементы как в примере выше, потом складываем результаты умножения
torch.matmul(tensor, tensor)

tensor(14)

In [42]:
# pytorch methods are very optimized:
%%time
val = 0
for i in range(len(tensor)):   
    val += tensor[i]*tensor[i]
print(val)

tensor(14)
CPU times: user 1.46 ms, sys: 944 µs, total: 2.41 ms
Wall time: 2.43 ms


In [43]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 87 µs, sys: 764 µs, total: 851 µs
Wall time: 646 µs


tensor(14)

### Two main rules for matrix multiplication:
1. The **inner dimentions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimentions**:
* `(2, 3) @ (3, 2)` -> shape(3, 3)
* `(2, 2) @ (2, 3)` -> shape(2, 3)

In [54]:
torch.matmul(torch.rand(2,2), torch.rand(2,3))

tensor([[0.5077, 0.3978, 0.2525],
        [0.5818, 0.5495, 0.4941]])

In [52]:
torch.rand(2,2)

tensor([[0.1979, 0.8274],
        [0.5251, 0.7471]])

In [53]:
torch.rand(2,3)

tensor([[0.9147, 0.4375, 0.5584],
        [0.5508, 0.7556, 0.8965]])

In [55]:
tensor_A = torch.tensor([
    [1,2],
    [3,4],
    [5,6]
])

In [56]:
tensor_B = torch.tensor([
    [7,8],
    [8,9],
    [9,9]
])

In [57]:
# torch.mm - alias for matmul
torch.mm(tensor_A, tensor_B)

RuntimeError: ignored

In [58]:
# RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)
# To fix this we can manipulate on of the tensors using a **transpose**

In [59]:
# transpose switches the axes or dimentions of a given tensor
tensor_B

tensor([[7, 8],
        [8, 9],
        [9, 9]])

In [61]:
# T - transpose
tensor_B.T

tensor([[7, 8, 9],
        [8, 9, 9]])