In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

1.13.1+cu116


## Tensors

### Creating Tensors

https://pytorch.org/docs/stable/tensors.html

In [3]:
# Scalar tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# Number of tensor dimentions
scalar.ndim

0

In [5]:
# Get tensor back as py int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector.ndim

1

In [7]:
vector

tensor([7, 7])

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([
    [7,8],
    [9,11]
])
MATRIX

tensor([[ 7,  8],
        [ 9, 11]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 11])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
#  TENSOR
TENSOR = torch.tensor([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random tensors

Why random tensors?

Random tensors, потому что многие нейронки учатся, начиная с тенсоров онли из рандомных чисел и потом подправляют их значения, чтобы лучше соответствовать данным

`Start with random numbers -> look at data -> update random nums -> look at data -> update randoom nums`

In [17]:
# Create a random tensors of size (2,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8222, 0.1931, 0.0235, 0.4256],
        [0.6307, 0.0104, 0.6084, 0.1414],
        [0.8641, 0.0925, 0.2754, 0.2431]])

In [18]:
random_tensor2 = torch.rand(10, 1, 3)
random_tensor2

tensor([[[0.1188, 0.6675, 0.1926]],

        [[0.1837, 0.4123, 0.2751]],

        [[0.4590, 0.2503, 0.6426]],

        [[0.8102, 0.1794, 0.9823]],

        [[0.7633, 0.8177, 0.2025]],

        [[0.0428, 0.4576, 0.2192]],

        [[0.5065, 0.7406, 0.5551]],

        [[0.8686, 0.8056, 0.4690]],

        [[0.6661, 0.1645, 0.0850]],

        [[0.9712, 0.0946, 0.5323]]])

In [19]:
random_tensor.shape

torch.Size([3, 4])

In [20]:
random_tensor2.shape

torch.Size([10, 1, 3])

In [21]:
random_tensor2.ndim

3

In [22]:
# random tensor with similar shape to an image tensor
# size - optional keyword, not really needed
rnd_img_size_tensor = torch.rand(size=(224, 224, 3)) #h, w, color chanels
rnd_img_size_tensor.shape, rnd_img_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeroes and ones

In [23]:
# tensor of all zeros
zeros = torch.zeros(3,5)
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [24]:
ones = torch.ones(3,5)
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

### Creatingrange of tensors and tensors-like

In [25]:
# torch.range() rкак и python range()
x = torch.arange(0, 10, 2)
x

tensor([0, 2, 4, 6, 8])

In [26]:
# creating tensors-like, создает тенсор из нулей(например), такой-же формы(shape), как переданный тенсор
five_zeros = torch.zeros_like(x)
five_zeros

tensor([0, 0, 0, 0, 0])

### Tensor datatypes
##### 3 main issues when working with pytorrch and deep learning:
1. Tensors not right dtype
2. Tensors not right shape
3. Tensors not on the right device

In [27]:
#float 32
float_32_tensor = torch.tensor([1,3,3,7], dtype=torch.float32)
float_32_tensor

tensor([1., 3., 3., 7.])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
float_32_tensor2 = torch.tensor([1,3,3.,7])
float_32_tensor2

tensor([1., 3., 3., 7.])

In [30]:
float_32_tensor2.dtype

torch.float32

In [31]:
float_32_tensor3 = torch.tensor([1.1, 2.2, 3.3], 
                                dtype=None, #what datatype is tensor
                                device=None, #cpu or gpu(cuda)
                                requires_grad=False #whether or not to track gradients
                                )
float_32_tensor3

tensor([1.1000, 2.2000, 3.3000])

In [32]:
float_32_tensor3.dtype

torch.float32

In [33]:
float_16 = float_32_tensor.type(torch.float16)
float_16

tensor([1., 3., 3., 7.], dtype=torch.float16)

In [34]:
float_16.device

device(type='cpu')

### Manupulating Tensors (operations)

To find patterns in numbers of dataset, the neural network will usually combine all of this:

* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [35]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [36]:
# multiply by 10
tensor * 10

tensor([10, 20, 30])

In [37]:
tensor - 10

tensor([-9, -8, -7])

#### Marix Multiplication (dot product)

Чтобы перемножить матрицы, нам нужно найти так называемый dot product колонок и рядов
https://www.mathsisfun.com/algebra/matrix-multiplying.html